// Generates every llms.txt artifact from the registry in src/data.
// Run: npm run llms  (also runs automatically before dev/build)
// Output is GENERATED — never hand-edit files under public/llms*.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { categories, entries, GROUP_LABELS, sources } from "../src/data/index";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");

const LICENSE_LABEL = { mit: "MIT", free: "Free", freemium: "Freemium", paid: "Paid" } as const;
const MODE_LABEL = { live: "live-previewable", linkout: "link-out only" } as const;

function entryLine(e: (typeof entries)[number]): string {
  const bits = [`- **${e.name}**`, e.sourceUrl];
  bits.push(`— ${e.description}`);
  bits.push(`[${LICENSE_LABEL[e.license]}, ${MODE_LABEL[e.previewMode]}, category: ${e.category}]`);
  return bits.join(" ");
}

function write(path: string, content: string) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
  console.log(
    `wrote ${path.replace(root + "\\", "").replace(root + "/", "")} (${content.length} bytes)`,
  );
}

const bySource = new Map(sources.map((s) => [s.id, entries.filter((e) => e.source === s.id)]));
const byCategory = new Map(
  categories.map((c) => [c.slug, entries.filter((e) => e.category === c.slug)]),
);

// ---- public/llms.txt — the index ----
{
  const lines: string[] = [
    "# UI Vault",
    "",
    "> A personal, frontend-only catalog of UI components aggregated from 12 curated sources",
    "> (animated React libraries, shadcn block registries, layout marketplaces and design galleries)",
    "> into one categorized, searchable library. Every entry records its source, license, install",
    "> command and — for open-source sources — a live React preview. No backend: the catalog itself",
    `> lives in TypeScript files under src/data (${entries.length} entries, ${sources.length} sources, ${categories.length} categories).`,
    "",
    "## Sources",
    "",
  ];
  for (const s of sources) {
    const count = bySource.get(s.id)!.length;
    lines.push(
      `- [${s.name}](${s.url}) — ${s.tagline} (${LICENSE_LABEL[s.license]}, ${MODE_LABEL[s.previewMode]}, ${count} cataloged)`,
    );
  }
  lines.push("", "## Categories", "");
  for (const group of ["components", "blocks", "templates", "inspiration"] as const) {
    lines.push(`### ${GROUP_LABELS[group]}`);
    for (const c of categories.filter((c) => c.group === group)) {
      lines.push(
        `- \`${c.slug}\` ${c.name} (${byCategory.get(c.slug)!.length}) — ${c.description}`,
      );
    }
    lines.push("");
  }
  lines.push(
    "## Links",
    "",
    "- [llms-full.txt](llms-full.txt): the complete catalog in one file",
    "- [Sources](llms/sources/): one page per source",
    "- [Categories](llms/categories/): one page per category",
    "- Generated by `npm run llms` from src/data — do not edit by hand.",
    "",
  );
  write(join(publicDir, "llms.txt"), lines.join("\n"));
}

// ---- per-source pages ----
for (const s of sources) {
  const list = bySource.get(s.id)!;
  const lines = [
    `# ${s.name}`,
    "",
    `> ${s.tagline}`,
    "",
    `- URL: ${s.url}`,
    `- License: ${LICENSE_LABEL[s.license]} — ${MODE_LABEL[s.previewMode]}`,
    `- Stack: ${s.stack.join(", ")}`,
    s.install ? `- Install: \`${s.install}\`` : "- Install: n/a (link-out)",
    s.notes ? `- Notes: ${s.notes}` : "",
    `- Cataloged in UI Vault: ${list.length} entries`,
    "",
    "## Entries",
    "",
    ...list.map(entryLine),
    "",
  ].filter((l) => l !== "");
  write(join(publicDir, "llms", "sources", `${s.id}.md`), lines.join("\n"));
}

// ---- per-category pages ----
for (const c of categories) {
  const list = byCategory.get(c.slug)!;
  const lines = [
    `# ${c.name} (\`${c.slug}\`)`,
    "",
    `> ${c.description} — group: ${GROUP_LABELS[c.group]}`,
    "",
    "## Entries",
    "",
    ...(list.length ? list.map(entryLine) : ["(none yet)"]),
    "",
  ];
  write(join(publicDir, "llms", "categories", `${c.slug}.md`), lines.join("\n"));
}

// ---- llms-full.txt — everything ----
{
  const lines: string[] = [
    "# UI Vault — full catalog",
    "",
    `> ${entries.length} entries from ${sources.length} sources. Generated by \`npm run llms\`.`,
    "",
    "## Sources",
    "",
    ...sources.map(
      (s) =>
        `### ${s.name} — ${s.url}\n${s.description}\nLicense: ${LICENSE_LABEL[s.license]}. Install: ${s.install ?? "n/a"}.`,
    ),
    "",
    "## All entries by category",
    "",
  ];
  for (const c of categories) {
    const list = byCategory.get(c.slug)!;
    if (!list.length) continue;
    lines.push(`### ${c.name} (${c.slug})`);
    lines.push(...list.map(entryLine));
    lines.push("");
  }
  write(join(publicDir, "llms-full.txt"), lines.join("\n"));
}

console.log(
  `\nllms.txt artifacts generated: ${entries.length} entries across ${sources.length} sources.`,
);
