import type { UIEntry } from "../types";

// https://pro.ui-layouts.com — paid ($139+). LINK-OUT ONLY.
// Block categories: Herosec / Experience / Testimonial / About / Feature / Pricing.
export const uilayouts: UIEntry[] = [
  {
    id: "uilayouts-hero-collection",
    name: "Hero Section Collection (26+)",
    description:
      "The flagship collection: 26+ full-page hero layouts, each viewable as shadcn, Tailwind or Motion variants.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/hero",
    sourceCategory: "Herosec",
    category: "hero",
    tags: ["hero", "collection", "layout", "paid"],
    license: "paid",
    previewMode: "linkout",
    featured: true,
  },
  {
    id: "uilayouts-agency-hero",
    name: "Agency Hero",
    description: "Bold agency hero — oversized type, image collage, strong CTA pairing.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/hero",
    sourceCategory: "Herosec",
    category: "hero",
    tags: ["hero", "agency", "bold"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-flowsync-hero",
    name: "FlowSync Hero",
    description: "SaaS workflow hero — product screenshot with flow accents.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/hero",
    sourceCategory: "Herosec",
    category: "hero",
    tags: ["hero", "saas", "workflow"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-streamline-hero",
    name: "Streamline Hero",
    description: "Minimal streamline hero — centered message, generous space.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/hero",
    sourceCategory: "Herosec",
    category: "hero",
    tags: ["hero", "minimal"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-workflow-automation-hero",
    name: "Workflow Automation Hero",
    description: "Automation-focused hero with diagram motifs and animated connectors.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/hero",
    sourceCategory: "Herosec",
    category: "hero",
    tags: ["hero", "automation", "diagram"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-experience-sections",
    name: "Experience Sections",
    description: "Work-experience and process sections — timelines and step flows.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/experience",
    sourceCategory: "Experience",
    category: "features",
    tags: ["experience", "timeline", "process"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-testimonial-sections",
    name: "Testimonial Sections",
    description: "Full testimonial layouts — walls, carousels and combined proof bars.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/testimonial",
    sourceCategory: "Testimonial",
    category: "testimonials",
    tags: ["testimonials", "sections"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-about-sections",
    name: "About Sections",
    description: "About-page compositions with imagery and narrative blocks.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/about",
    sourceCategory: "About",
    category: "sections-misc",
    tags: ["about", "story"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-feature-sections",
    name: "Feature Sections",
    description: "Feature layouts — grids, alternating rows and sticky scrollers.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/feature",
    sourceCategory: "Feature",
    category: "features",
    tags: ["features", "grid"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-pricing-sections",
    name: "Pricing Sections",
    description: "Pricing layouts with toggles and highlighted plans.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/blocks/pricing",
    sourceCategory: "Pricing",
    category: "pricing",
    tags: ["pricing", "plans"],
    license: "paid",
    previewMode: "linkout",
  },
  {
    id: "uilayouts-templates",
    name: "Full Site Templates",
    description:
      "Complete templates (Talentflow, MVPStudio, NextCodez and more) plus a drag-and-drop page builder that exports production code.",
    source: "uilayouts",
    sourceUrl: "https://pro.ui-layouts.com/templates",
    sourceCategory: "Templates",
    category: "full-templates",
    tags: ["templates", "builder", "full-site"],
    license: "paid",
    previewMode: "linkout",
  },
];
