import type { Source } from "./types";

export const sources: Source[] = [
  {
    id: "reactbits",
    name: "React Bits",
    url: "https://reactbits.dev",
    tagline: "Open-source animated, interactive & fully customizable React components.",
    description:
      "134 free MIT components across text animations, backgrounds, animations and interactive components, with TypeScript/JavaScript and Tailwind/CSS variants per component. Pro tier adds blocks and templates.",
    license: "mit",
    previewMode: "live",
    stack: ["react", "typescript", "tailwind", "motion", "gsap", "webgl"],
    install: "npx jsrepo add react-bits/<Component>",
    installLabel: "jsrepo CLI",
    notes:
      "Free tier is MIT (github.com/DavidHDev/react-bits). Pro is a separate paid tier — link-out only.",
    color: "#38bdf8",
  },
  {
    id: "motionprimitives",
    name: "Motion Primitives",
    url: "https://motion-primitives.com",
    tagline: "UI kit to make beautiful, animated interfaces, faster.",
    description:
      "~35 minimalist motion components by ibelick, built entirely on Motion (motion.dev). Every component is a copy-paste primitive with a dedicated CLI. Pro adds 50+ premium components and sections.",
    license: "mit",
    previewMode: "live",
    stack: ["react", "typescript", "tailwind", "motion"],
    install: "npx motion-primitives@latest add <name>",
    installLabel: "motion-primitives CLI",
    notes: "Free core is MIT. Pro ($149 one-time) is link-out only.",
    color: "#a78bfa",
  },
  {
    id: "fancy",
    name: "FancyComponents",
    url: "https://fancycomponents.dev",
    tagline: "Make the web fun again.",
    description:
      "~46 fun and weird components recreating effects from award-winning sites — letter swaps, gravity, elastic lines, gooey filters. Fully MIT and open source by danielpetho.",
    license: "mit",
    previewMode: "live",
    stack: ["react", "typescript", "tailwind", "motion"],
    install: "pnpm dlx shadcn add @fancy/<component>",
    installLabel: "shadcn registry (@fancy)",
    notes:
      'Registry: add {"registries": {"@fancy": "https://fancycomponents.dev/r/{name}.json"}} to components.json. MIT — vendor freely.',
    color: "#fb923c",
  },
  {
    id: "numberflow",
    name: "NumberFlow",
    url: "https://number-flow.barvian.me",
    tagline: "Animated number component, for React, Vue, Svelte & vanilla.",
    description:
      "The animated number (odometer/digit-spin) component. Dependency-free custom element + Web Animations API, reduced-motion aware, SSR friendly. 7.7k GitHub stars.",
    license: "mit",
    previewMode: "live",
    stack: ["react", "typescript", "css"],
    install: "npm i @number-flow/react",
    installLabel: "npm",
    notes: "Also ships @number-flow/vue, @number-flow/svelte and vanilla number-flow. MIT.",
    color: "#4ade80",
  },
  {
    id: "watermelon",
    name: "Watermelon UI",
    url: "https://watermelon.sh",
    tagline: "600+ free open-source components, 100+ animations, 230+ blocks.",
    description:
      "Fully open-source shadcn-style library: components, animated micro-interactions, section blocks and 10+ complete dashboards. Free forever for personal and commercial use.",
    license: "free",
    previewMode: "live",
    stack: ["react", "typescript", "tailwind", "shadcn", "motion", "vite"],
    install: "npx shadcn@latest add https://registry.watermelon.sh/r/<name>.json",
    installLabel: "shadcn registry",
    notes: "Open source (github.com/WatermelonCorp/watermelon-platform) — vendor freely.",
    color: "#fb7185",
  },
  {
    id: "aceternity",
    name: "Aceternity UI",
    url: "https://ui.aceternity.com",
    tagline: "The React component library for beautiful landing pages.",
    description:
      '200+ production-ready components and blocks that "look expensive" — parallax heroes, beams, shaders, docks. Free tier covers ~100 components; premium adds 200+ blocks and full templates.',
    license: "freemium",
    previewMode: "live",
    stack: ["react", "nextjs", "typescript", "tailwind", "motion", "three"],
    install: "npx aceternity-ui@latest add <name>",
    installLabel: "aceternity CLI",
    notes: "Free components only may be vendored. Premium blocks/templates are paid — link-out.",
    color: "#e879f9",
  },
  {
    id: "21st",
    name: "21st.dev",
    url: "https://21st.dev",
    tagline: "The living library of interfaces — 12,000+ community components.",
    description:
      "Huge community registry of React components, blocks and shadcn themes. Largest categories: Buttons (2,043), Forms (1,522), Heroes (1,152). Freemium: 2 component copies/day free.",
    license: "freemium",
    previewMode: "linkout",
    stack: ["react", "nextjs", "tailwind", "shadcn", "motion", "webgl"],
    install: "npx @21st/cli add <component-url>",
    installLabel: "21st CLI (account required)",
    notes: "Gated platform — link-out only, never vendor from here.",
    color: "#22d3ee",
  },
  {
    id: "shadcnstudio",
    name: "shadcnStudio",
    url: "https://shadcnstudio.com",
    tagline: "800+ shadcn blocks, 1000+ component variants.",
    description:
      "Massive shadcn/ui block library (Marketing UI, Dashboard & App, eCommerce, Bento, Datatable) plus themes, templates and a Figma kit. 67 free blocks; Pro is $249 lifetime.",
    license: "freemium",
    previewMode: "linkout",
    stack: ["react", "tailwind", "shadcn", "radix", "base-ui", "motion"],
    notes: "Free tier browseable; Pro is paid — link-out only.",
    color: "#cbd5e1",
  },
  {
    id: "uilayouts",
    name: "UI Layouts Pro",
    url: "https://pro.ui-layouts.com",
    tagline: "150+ premium full-page layout blocks and templates.",
    description:
      "Complete page-level layouts (26+ hero variants, features, testimonials, pricing) viewable as shadcn, Tailwind or Motion variants, plus a drag-and-drop template builder. $139 one-time.",
    license: "paid",
    previewMode: "linkout",
    stack: ["react", "nextjs", "tailwind", "shadcn", "motion"],
    notes:
      "Paid product ($139 Creator / $198 Forever Builder) — link-out only. Free sibling: ui-layouts.com.",
    color: "#facc15",
  },
  {
    id: "cue",
    name: "Cue",
    url: "https://cuedesign.space",
    tagline: "Awwwards-tier component references, delivered as AI prompts.",
    description:
      "92 hand-curated components sourced from Sites of the Day. Each ships an AI prompt you paste into Bolt, v0, Cursor or Claude. React source code rolling out; Cue+ is $99 lifetime.",
    license: "freemium",
    previewMode: "linkout",
    stack: ["prompt-based", "react (rolling out)"],
    notes: "Prompt/reference layer — link-out only.",
    color: "#ec4899",
  },
  {
    id: "collectui",
    name: "CollectUI",
    url: "https://collectui.com",
    tagline: "Hand-curated daily gallery of the best UI on the web — 147 categories.",
    description:
      "Visual inspiration gallery of Dribbble-style designs organized into 147 categories (Dashboard, Sign Up, Pricing, Music Player, Dynamic Island…). Pure pattern recognition fuel.",
    license: "free",
    previewMode: "linkout",
    stack: ["reference only"],
    notes: "Screenshots + link-outs, no code — inspiration only.",
    color: "#2dd4bf",
  },
  {
    id: "componentgallery",
    name: "The Component Gallery",
    url: "https://component.gallery",
    tagline: "Component patterns from 95 design systems — 2,671 examples.",
    description:
      "Reference of 60 component patterns, each aggregating real screenshots from design systems (Polaris, Elastic EUI, Ariakit, HeroUI…) with links to docs, GitHub and Figma.",
    license: "free",
    previewMode: "linkout",
    stack: ["reference only"],
    notes: "Pattern reference — link-out only.",
    color: "#a3a3a3",
  },
];
