import type { UIEntry } from "../types";

// https://fancycomponents.dev — MIT. Live-vendorable.
// Upstream groups: Text / Carousel / Background / Physics / Image / Filter / Blocks.
export const fancy: UIEntry[] = [
  {
    id: "fancy-letter-swap",
    name: "Letter Swap",
    description:
      "On hover, letters scramble through glyphs and settle one by one — playful link/button treatment.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/text/letter-swap",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "hover", "scramble", "letters"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/letter-swap",
    previewKey: "fancy-letter-swap",
    featured: true,
  },
  {
    id: "fancy-scramble-hover",
    name: "Scramble Hover",
    description: "Whole word scrambles and re-decodes when hovered — the decrypt effect on demand.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/text/scramble-hover",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "hover", "scramble"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/scramble-hover",
  },
  {
    id: "fancy-text-highlighter",
    name: "Text Highlighter",
    description: "Marker-pen highlight sweeps across text as you scroll — hand-drawn emphasis.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/text/text-highlighter",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "highlight", "scroll", "marker"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/text-highlighter",
  },
  {
    id: "fancy-typewriter",
    name: "Typewriter",
    description:
      "Types and deletes text with a blinking caret and loop — the dependable typewriter.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/text/typewriter",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "typing", "caret", "loop"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/typewriter",
    previewKey: "fancy-typewriter",
  },
  {
    id: "fancy-number-ticker",
    name: "Number Ticker",
    description: "Scroll-triggered number roll-up with spring easing — stats sections love this.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/text/basic-number-ticker",
    sourceCategory: "Text",
    category: "numbers",
    tags: ["number", "scroll", "counter", "spring"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/number-ticker",
  },
  {
    id: "fancy-gravity",
    name: "Gravity",
    description:
      "Elements fall with real physics and collide, reacting to your pointer — matter.js playground.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/physics/gravity",
    sourceCategory: "Physics",
    category: "micro-interactions",
    tags: ["physics", "gravity", "matter", "playful"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/gravity",
    featured: true,
  },
  {
    id: "fancy-elastic-line",
    name: "Elastic Line",
    description:
      "A draggable elastic line that wobbles back into place — irresistible micro-interaction.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/physics/elastic-line",
    sourceCategory: "Physics",
    category: "micro-interactions",
    tags: ["physics", "elastic", "drag", "svg"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/elastic-line",
  },
  {
    id: "fancy-image-trail",
    name: "Image Trail",
    description:
      "A trail of images follows the cursor with staggered physics — editorial site energy.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/image/image-trail",
    sourceCategory: "Image",
    category: "micro-interactions",
    tags: ["images", "cursor", "trail", "physics"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/image-trail",
  },
  {
    id: "fancy-pixel-trail",
    name: "Pixel Trail",
    description: "Pixelated squares trail the cursor and fade — retro cursor confetti.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/background/pixel-trail",
    sourceCategory: "Image",
    category: "micro-interactions",
    tags: ["pixel", "cursor", "trail", "retro"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/pixel-trail",
  },
  {
    id: "fancy-gooey-svg-filter",
    name: "Gooey SVG Filter",
    description:
      "SVG goo filter that merges moving blobs into liquid metal — the metaball trick in pure SVG.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/filter/gooey-svg-filter",
    sourceCategory: "Filter",
    category: "backgrounds",
    tags: ["svg", "filter", "gooey", "blobs"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/gooey-svg-filter",
  },
  {
    id: "fancy-pixelate-svg-filter",
    name: "Pixelate SVG Filter",
    description: "Pixelation filter for images — hover to pixelate/de-pixelate transitions.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/filter/pixelate-svg-filter",
    sourceCategory: "Filter",
    category: "backgrounds",
    tags: ["svg", "filter", "pixel", "retro"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/pixelate-svg-filter",
  },
  {
    id: "fancy-css-box",
    name: "CSS Box",
    description:
      "A box that skeuomorphically wobbles, tilts and reacts — physics-y container demo.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/blocks/css-box",
    sourceCategory: "Physics",
    category: "micro-interactions",
    tags: ["box", "physics", "wobble"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/css-box",
  },
  {
    id: "fancy-screensaver",
    name: "Screensaver",
    description: "DVD-logo-style bouncing screensaver for any element — nostalgia as a service.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/blocks/screensaver",
    sourceCategory: "Physics",
    category: "micro-interactions",
    tags: ["screensaver", "bounce", "retro", "dvd"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/screensaver",
  },
  {
    id: "fancy-stacking-cards",
    name: "Stacking Cards",
    description:
      "Cards stack and scale on scroll like a deck being dealt — the classic scroll narrative.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/blocks/stacking-cards",
    sourceCategory: "Carousel",
    category: "cards",
    tags: ["cards", "stack", "scroll", "sticky"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/stacking-cards",
  },
  {
    id: "fancy-marquee-along-svg-path",
    name: "Marquee Along SVG Path",
    description: "Content marquees along any SVG path — text or images flowing along a curve.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/blocks/marquee-along-svg-path",
    sourceCategory: "Carousel",
    category: "sections-misc",
    tags: ["marquee", "svg", "path", "motion-path"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/marquee-along-svg-path",
  },
  {
    id: "fancy-media-between-text",
    name: "Media Between Text",
    description:
      "Video/image peeks out between two lines of text on hover — the award-site hero trick.",
    source: "fancy",
    sourceUrl: "https://www.fancycomponents.dev/docs/components/blocks/media-between-text",
    sourceCategory: "Blocks",
    category: "sections-misc",
    tags: ["text", "media", "hover", "editorial"],
    license: "mit",
    previewMode: "live",
    install: "pnpm dlx shadcn add @fancy/media-between-text",
  },
];
