import type { UIEntry } from "../types";

// https://21st.dev — community registry, freemium (2 copies/day). LINK-OUT ONLY.
// Upstream groups: Marketing Blocks / UI Components.
export const twentyfirst: UIEntry[] = [
  {
    id: "21st-interactive-globe",
    name: "Interactive Globe",
    description:
      "Canvas 3D globes with draggable rotation and location pulses, from the community.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/globe",
    sourceCategory: "Globes",
    category: "3d-webgl",
    tags: ["globe", "canvas", "3d", "map"],
    license: "freemium",
    previewMode: "linkout",
    featured: true,
  },
  {
    id: "21st-buttons-gallery",
    name: "Buttons — Community Gallery",
    description:
      "The largest category on 21st.dev: 2,043 community button components with micro-interactions.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/button",
    sourceCategory: "Buttons",
    category: "buttons",
    tags: ["gallery", "community", "buttons"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-heroes-gallery",
    name: "Heroes — Community Gallery",
    description:
      "1,152 hero section components from the community — every style from minimal to shader-heavy.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/hero",
    sourceCategory: "Heroes",
    category: "hero",
    tags: ["gallery", "community", "hero"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-forms-gallery",
    name: "Forms — Community Gallery",
    description: "1,522 form components — validators, multi-step flows, OTP and more.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/form",
    sourceCategory: "Forms",
    category: "forms",
    tags: ["gallery", "community", "forms"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-inputs-gallery",
    name: "Inputs — Community Gallery",
    description: "949 input components — floating labels, masks, animated focus states.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/input",
    sourceCategory: "Inputs",
    category: "forms",
    tags: ["gallery", "community", "inputs"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-texts-gallery",
    name: "Texts — Community Gallery",
    description: "663 text effect components — animations for every typographic mood.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/text",
    sourceCategory: "Texts",
    category: "text-animation",
    tags: ["gallery", "community", "text"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-backgrounds-gallery",
    name: "Backgrounds — Community Gallery",
    description: "Generative backgrounds — gradients, shaders (new category), meshes and grids.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/background",
    sourceCategory: "Backgrounds",
    category: "backgrounds",
    tags: ["gallery", "community", "backgrounds"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-ai-chats",
    name: "AI Chat Components",
    description:
      "Chat interfaces for AI products — message streams, typing indicators, prompt bars.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/ai-chat",
    sourceCategory: "AI Chats",
    category: "overlays",
    tags: ["ai", "chat", "streaming"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-dashboards-gallery",
    name: "Dashboards — Community Gallery",
    description:
      "Full dashboard layouts from the community, including collapsible-sidebar variants.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/dashboard",
    sourceCategory: "Dashboards",
    category: "dashboards",
    tags: ["gallery", "community", "dashboard"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-file-trees",
    name: "File Trees",
    description: "Collapsible file-tree components — code viewers and docs sidebars.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/file-tree",
    sourceCategory: "File Trees",
    category: "navigation",
    tags: ["tree", "file", "collapse"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-stats-bento",
    name: "Stats Bento",
    description: "Popular stats/KPI bento grid block — metrics in a tight Apple-style grid.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/stat",
    sourceCategory: "Stats & KPIs",
    category: "data-display",
    tags: ["bento", "stats", "kpi"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-faq-cards-grid",
    name: "FAQ Cards Grid",
    description: "Popular FAQ block — questions as expandable cards in a grid.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/faq",
    sourceCategory: "FAQs",
    category: "faq",
    tags: ["faq", "cards", "grid"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-pricing-gallery",
    name: "Pricing Sections",
    description: "Community pricing sections — toggles, comparisons, highlighted plans.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/pricing-section",
    sourceCategory: "Pricing Sections",
    category: "pricing",
    tags: ["gallery", "pricing", "sections"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-testimonials-gallery",
    name: "Testimonials",
    description: "Community testimonial sections — walls, marquees and featured quotes.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/testimonials",
    sourceCategory: "Testimonials",
    category: "testimonials",
    tags: ["gallery", "testimonials"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-onboarding",
    name: "Onboarding Flows",
    description: "Onboarding components — carousels, checklists and progress experiences.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/onboarding",
    sourceCategory: "Onboarding",
    category: "sections-misc",
    tags: ["onboarding", "flow"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-cursors",
    name: "Custom Cursors",
    description: "Cursor components — followers, spots, magnetic dots.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/cursor",
    sourceCategory: "Cursors",
    category: "micro-interactions",
    tags: ["cursor", "pointer"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-notifications",
    name: "Notifications & Toasts",
    description: "Toast and notification components — stacked, animated, actionable.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/notification",
    sourceCategory: "Notifications",
    category: "feedback",
    tags: ["toast", "notification"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-empty-states",
    name: "Empty States",
    description: "Empty-state components — friendly placeholders when there is nothing to show.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/empty-state",
    sourceCategory: "Empty States",
    category: "feedback",
    tags: ["empty", "placeholder"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-bloom-field-gradient",
    name: "Bloom Field Gradient",
    description: "Popular organic gradient background — blooming color fields for heroes.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/gradient",
    sourceCategory: "Backgrounds",
    category: "backgrounds",
    tags: ["gradient", "organic", "hero"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-navigation-menus",
    name: "Navigation Menus",
    description:
      "Navbar and navigation-menu components — sticky headers, mega menus, hamburger patterns.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/navigation-menu",
    sourceCategory: "Navigation Menu",
    category: "navbars",
    tags: ["gallery", "community", "navbar", "menu"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-galleries",
    name: "Gallery Components",
    description:
      "Image gallery components — grids, lightboxes and masonry layouts from the community.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/components/s/gallery",
    sourceCategory: "Gallery",
    category: "galleries",
    tags: ["gallery", "community", "images", "grid"],
    license: "freemium",
    previewMode: "linkout",
  },
  {
    id: "21st-magic-ui-collection",
    name: "Magic UI Collection",
    description:
      "The Magic UI library republished on 21st.dev as a 63-component collection — animations, buttons, heroes.",
    source: "21st",
    sourceUrl: "https://21st.dev/community/dillionverma/library/magic-ui",
    sourceCategory: "Hooks & Libraries",
    category: "sections-misc",
    tags: ["collection", "magic-ui", "library"],
    license: "freemium",
    previewMode: "linkout",
  },
];
