import type { UIEntry } from "../types";

// https://motion-primitives.com — MIT free tier. Live-vendorable.
// Prerequisites: motion, tailwind, lucide-react, cn().
export const motionprimitives: UIEntry[] = [
  {
    id: "motionprimitives-text-effect",
    name: "TextEffect",
    description:
      "Per-character text animation with blur, slide and fade presets — the workhorse reveal primitive.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/text-effect",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "per-letter", "reveal", "spring"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add text-effect",
    previewKey: "motionprimitives-text-effect",
    featured: true,
  },
  {
    id: "motionprimitives-text-scramble",
    name: "Text Scramble",
    description: "Characters shuffle through random glyphs before locking into place.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/text-scramble",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "scramble", "decode"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add text-scramble",
  },
  {
    id: "motionprimitives-text-morph",
    name: "Text Morph",
    description: "Morphs one word into another, interpolating letters smoothly.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/text-morph",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "morph", "words"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add text-morph",
  },
  {
    id: "motionprimitives-text-roll",
    name: "Text Roll",
    description: "Rolling column of words that cycles with a vertical roll transition.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/text-roll",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "roll", "rotator"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add text-roll",
  },
  {
    id: "motionprimitives-shimmer-wave",
    name: "Shimmer Wave",
    description:
      "A shimmer sweep travels across the text in a wave — premium loading or heading accent.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/shimmer-wave",
    sourceCategory: "Text",
    category: "text-animation",
    tags: ["text", "shimmer", "wave", "shine"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add shimmer-wave",
  },
  {
    id: "motionprimitives-animated-number",
    name: "Animated Number",
    description:
      "Spring-animated number transitions — buttery odometer without Web Animations API.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/animated-number",
    sourceCategory: "Interaction",
    category: "numbers",
    tags: ["number", "spring", "counter"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add animated-number",
  },
  {
    id: "motionprimitives-sliding-number",
    name: "Sliding Number",
    description: "Digits slide vertically on value change — the split-flap board feel.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/sliding-number",
    sourceCategory: "Interaction",
    category: "numbers",
    tags: ["number", "slide", "digits"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add sliding-number",
  },
  {
    id: "motionprimitives-border-trail",
    name: "Border Trail",
    description:
      "A light trail runs along the border of any box — living outlines for cards and inputs.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/border-trail",
    sourceCategory: "Interaction",
    category: "cards",
    tags: ["border", "trail", "glow", "card"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add border-trail",
  },
  {
    id: "motionprimitives-spotlight",
    name: "Spotlight",
    description:
      "Hover spotlight that follows the cursor across a card, revealing content beneath.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/spotlight",
    sourceCategory: "Interaction",
    category: "cards",
    tags: ["spotlight", "hover", "card", "pointer"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add spotlight",
  },
  {
    id: "motionprimitives-glow-effect",
    name: "Glow Effect",
    description:
      "Soft radial glow that tracks the pointer over any element — subtle depth on hover.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/glow-effect",
    sourceCategory: "Interaction",
    category: "cards",
    tags: ["glow", "hover", "pointer", "radial"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add glow-effect",
    previewKey: "motionprimitives-glow-effect",
  },
  {
    id: "motionprimitives-tilt",
    name: "Tilt",
    description: "Pointer-tracked 3D tilt with spring return — physical depth for cards.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/tilt",
    sourceCategory: "Interaction",
    category: "micro-interactions",
    tags: ["tilt", "3d", "pointer", "card"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add tilt",
  },
  {
    id: "motionprimitives-magnetic",
    name: "Magnetic",
    description:
      "Elements gravitate toward the cursor with spring physics — magnetic buttons and icons.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/magnetic",
    sourceCategory: "Interaction",
    category: "micro-interactions",
    tags: ["magnetic", "pointer", "spring"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add magnetic",
  },
  {
    id: "motionprimitives-dock",
    name: "Dock",
    description: "macOS-style magnifying dock with spring scaling on hover.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/dock",
    sourceCategory: "Interaction",
    category: "navigation",
    tags: ["dock", "magnify", "macos", "spring"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add dock",
  },
  {
    id: "motionprimitives-morphing-dialog",
    name: "Morphing Dialog",
    description:
      "Dialog that morphs open from its trigger element — the Apple-style continuous transition.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/morphing-dialog",
    sourceCategory: "Interaction",
    category: "overlays",
    tags: ["dialog", "morph", "layout", "modal"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add morphing-dialog",
    featured: true,
  },
  {
    id: "motionprimitives-morphing-popover",
    name: "Morphing Popover",
    description:
      "Popover that springs morphs from its anchor — lightweight overlay with layout continuity.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/morphing-popover",
    sourceCategory: "Interaction",
    category: "overlays",
    tags: ["popover", "morph", "overlay"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add morphing-popover",
  },
  {
    id: "motionprimitives-infinite-slider",
    name: "Infinite Slider",
    description: "Infinite marquee slider — logos, testimonials, anything on a loop.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/infinite-slider",
    sourceCategory: "Interaction",
    category: "micro-interactions",
    tags: ["marquee", "infinite", "loop", "slider"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add infinite-slider",
  },
  {
    id: "motionprimitives-scroll-progress",
    name: "Scroll Progress",
    description: "Slim progress bar tracking page or container scroll position.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/scroll-progress",
    sourceCategory: "Interaction",
    category: "navigation",
    tags: ["scroll", "progress", "bar"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add scroll-progress",
  },
  {
    id: "motionprimitives-cursor",
    name: "Cursor",
    description:
      "Custom animated cursor with follower physics — replaces the system pointer tastefully.",
    source: "motionprimitives",
    sourceUrl: "https://motion-primitives.com/docs/cursor",
    sourceCategory: "Interaction",
    category: "micro-interactions",
    tags: ["cursor", "follower", "pointer"],
    license: "mit",
    previewMode: "live",
    install: "npx motion-primitives@latest add cursor",
  },
];
