import type { ComponentType } from "react";

/**
 * Lazy loaders for vendored live previews, keyed by UIEntry.previewKey.
 * One folder per component under src/showcase/<source>/<name>/preview.tsx.
 */
export const showcaseLoaders: Record<string, () => Promise<{ default: ComponentType }>> = {
  "reactbits-split-text": () => import("./reactbits/split-text/preview"),
  "reactbits-blur-text": () => import("./reactbits/blur-text/preview"),
  "reactbits-glitch-text": () => import("./reactbits/glitch-text/preview"),
  "reactbits-decrypted-text": () => import("./reactbits/decrypted-text/preview"),
  "reactbits-gradient-text": () => import("./reactbits/gradient-text/preview"),
  "reactbits-circular-text": () => import("./reactbits/circular-text/preview"),
  "reactbits-shiny-text": () => import("./reactbits/shiny-text/preview"),
  "reactbits-count-up": () => import("./reactbits/count-up/preview"),
  "reactbits-scroll-reveal": () => import("./reactbits/scroll-reveal/preview"),
  "reactbits-fade-content": () => import("./reactbits/fade-content/preview"),
  "reactbits-click-spark": () => import("./reactbits/click-spark/preview"),
  "reactbits-splash-cursor": () => import("./reactbits/splash-cursor/preview"),
  "reactbits-meta-balls": () => import("./reactbits/meta-balls/preview"),
  "reactbits-silk": () => import("./reactbits/silk/preview"),
  "reactbits-liquid-chrome": () => import("./reactbits/liquid-chrome/preview"),
  "reactbits-hyperspeed": () => import("./reactbits/hyperspeed/preview"),
  "reactbits-iridescence": () => import("./reactbits/iridescence/preview"),
  "reactbits-ballpit": () => import("./reactbits/ballpit/preview"),
  "reactbits-dither": () => import("./reactbits/dither/preview"),
  "reactbits-ribbons": () => import("./reactbits/ribbons/preview"),
  "reactbits-particles": () => import("./reactbits/particles/preview"),
  "reactbits-elastic-mesh": () => import("./reactbits/elastic-mesh/preview"),
  "reactbits-lanyard": () => import("./reactbits/lanyard/preview"),
  "reactbits-magnet": () => import("./reactbits/magnet/preview"),
  "reactbits-star-border": () => import("./reactbits/star-border/preview"),
  "motionprimitives-text-effect": () => import("./motionprimitives/text-effect/preview"),
  "motionprimitives-text-scramble": () => import("./motionprimitives/text-scramble/preview"),
  "motionprimitives-text-morph": () => import("./motionprimitives/text-morph/preview"),
  "motionprimitives-text-roll": () => import("./motionprimitives/text-roll/preview"),
  "motionprimitives-shimmer-wave": () => import("./motionprimitives/shimmer-wave/preview"),
  "motionprimitives-animated-number": () => import("./motionprimitives/animated-number/preview"),
  "motionprimitives-sliding-number": () => import("./motionprimitives/sliding-number/preview"),
  "motionprimitives-border-trail": () => import("./motionprimitives/border-trail/preview"),
  "motionprimitives-spotlight": () => import("./motionprimitives/spotlight/preview"),
  "motionprimitives-glow-effect": () => import("./motionprimitives/glow-effect/preview"),
  "motionprimitives-tilt": () => import("./motionprimitives/tilt/preview"),
  "motionprimitives-magnetic": () => import("./motionprimitives/magnetic/preview"),
  "motionprimitives-dock": () => import("./motionprimitives/dock/preview"),
  "motionprimitives-morphing-dialog": () => import("./motionprimitives/morphing-dialog/preview"),
  "motionprimitives-morphing-popover": () => import("./motionprimitives/morphing-popover/preview"),
  "motionprimitives-infinite-slider": () => import("./motionprimitives/infinite-slider/preview"),
  "motionprimitives-scroll-progress": () => import("./motionprimitives/scroll-progress/preview"),
  "motionprimitives-cursor": () => import("./motionprimitives/cursor/preview"),
  "fancy-letter-swap": () => import("./fancy/letter-swap/preview"),
  "fancy-scramble-hover": () => import("./fancy/scramble-hover/preview"),
  "fancy-text-highlighter": () => import("./fancy/text-highlighter/preview"),
  "fancy-typewriter": () => import("./fancy/typewriter/preview"),
  "fancy-number-ticker": () => import("./fancy/number-ticker/preview"),
  "fancy-gravity": () => import("./fancy/gravity/preview"),
  "fancy-elastic-line": () => import("./fancy/elastic-line/preview"),
  "fancy-image-trail": () => import("./fancy/image-trail/preview"),
  "fancy-pixel-trail": () => import("./fancy/pixel-trail/preview"),
  "fancy-gooey-svg-filter": () => import("./fancy/gooey-svg-filter/preview"),
  "fancy-pixelate-svg-filter": () => import("./fancy/pixelate-svg-filter/preview"),
  "fancy-css-box": () => import("./fancy/css-box/preview"),
  "fancy-screensaver": () => import("./fancy/screensaver/preview"),
  "fancy-stacking-cards": () => import("./fancy/stacking-cards/preview"),
  "fancy-marquee-along-svg-path": () => import("./fancy/marquee-along-svg-path/preview"),
  "fancy-media-between-text": () => import("./fancy/media-between-text/preview"),
  "aceternity-moving-border": () => import("./aceternity/moving-border/preview"),
  "aceternity-3d-pin": () => import("./aceternity/3d-pin/preview"),
  "aceternity-3d-card-effect": () => import("./aceternity/3d-card-effect/preview"),
  "aceternity-hero-parallax": () => import("./aceternity/hero-parallax/preview"),
  "aceternity-lamp-effect": () => import("./aceternity/lamp-effect/preview"),
  "aceternity-macbook-scroll": () => import("./aceternity/macbook-scroll/preview"),
  "aceternity-background-beams": () => import("./aceternity/background-beams/preview"),
  "aceternity-aurora-background": () => import("./aceternity/aurora-background/preview"),
  "aceternity-wavy-background": () => import("./aceternity/wavy-background/preview"),
  "aceternity-infinite-moving-cards": () => import("./aceternity/infinite-moving-cards/preview"),
  "aceternity-tracing-beam": () => import("./aceternity/tracing-beam/preview"),
  "aceternity-text-generate-effect": () => import("./aceternity/text-generate-effect/preview"),
  "aceternity-floating-dock": () => import("./aceternity/floating-dock/preview"),
  "aceternity-bento-grid": () => import("./aceternity/bento-grid/preview"),
  "aceternity-github-globe": () => import("./aceternity/github-globe/preview"),
  "numberflow-numberflow": () => import("./numberflow/numberflow/preview"),
  "numberflow-group": () => import("./numberflow/group/preview"),
  "numberflow-input": () => import("./numberflow/input/preview"),
  "numberflow-countdown": () => import("./numberflow/countdown/preview"),
  "watermelon-card-split-accordion": () => import("./watermelon/card-split-accordion/preview"),
  "watermelon-micro-interactions": () => import("./watermelon/micro-interactions/preview"),
  "watermelon-hero-blocks": () => import("./watermelon/hero-blocks/preview"),
  "watermelon-footer-blocks": () => import("./watermelon/footer-blocks/preview"),
  "watermelon-auth-blocks": () => import("./watermelon/auth-blocks/preview"),
  "watermelon-pricing-blocks": () => import("./watermelon/pricing-blocks/preview"),
  "watermelon-faq-blocks": () => import("./watermelon/faq-blocks/preview"),
  "watermelon-testimonial-blocks": () => import("./watermelon/testimonial-blocks/preview"),
  "watermelon-cta-blocks": () => import("./watermelon/cta-blocks/preview"),
  "watermelon-dashboard-agndex": () => import("./watermelon/dashboard-agndex/preview"),
  "watermelon-dashboard-astrix": () => import("./watermelon/dashboard-astrix/preview"),
  "watermelon-dashboard-jobtracker": () => import("./watermelon/dashboard-jobtracker/preview"),
  "shadcn-accordion": () => import("./shadcn/accordion/preview"),
  "shadcn-alert": () => import("./shadcn/alert/preview"),
  "shadcn-alert-dialog": () => import("./shadcn/alert-dialog/preview"),
  "shadcn-aspect-ratio": () => import("./shadcn/aspect-ratio/preview"),
  "shadcn-attachment": () => import("./shadcn/attachment/preview"),
  "shadcn-avatar": () => import("./shadcn/avatar/preview"),
  "shadcn-badge": () => import("./shadcn/badge/preview"),
  "shadcn-breadcrumb": () => import("./shadcn/breadcrumb/preview"),
  "shadcn-bubble": () => import("./shadcn/bubble/preview"),
  "shadcn-button": () => import("./shadcn/button/preview"),
  "shadcn-button-group": () => import("./shadcn/button-group/preview"),
  "shadcn-calendar": () => import("./shadcn/calendar/preview"),
  "shadcn-card": () => import("./shadcn/card/preview"),
  "shadcn-carousel": () => import("./shadcn/carousel/preview"),
  "shadcn-chart": () => import("./shadcn/chart/preview"),
  "shadcn-checkbox": () => import("./shadcn/checkbox/preview"),
  "shadcn-collapsible": () => import("./shadcn/collapsible/preview"),
  "shadcn-combobox": () => import("./shadcn/combobox/preview"),
  "shadcn-command": () => import("./shadcn/command/preview"),
  "shadcn-context-menu": () => import("./shadcn/context-menu/preview"),
  "shadcn-data-table": () => import("./shadcn/data-table/preview"),
  "shadcn-date-picker": () => import("./shadcn/date-picker/preview"),
  "shadcn-dialog": () => import("./shadcn/dialog/preview"),
  "shadcn-direction": () => import("./shadcn/direction/preview"),
  "shadcn-drawer": () => import("./shadcn/drawer/preview"),
  "shadcn-dropdown-menu": () => import("./shadcn/dropdown-menu/preview"),
  "shadcn-empty": () => import("./shadcn/empty/preview"),
  "shadcn-field": () => import("./shadcn/field/preview"),
  "shadcn-hover-card": () => import("./shadcn/hover-card/preview"),
  "shadcn-input": () => import("./shadcn/input/preview"),
  "shadcn-input-group": () => import("./shadcn/input-group/preview"),
  "shadcn-input-otp": () => import("./shadcn/input-otp/preview"),
  "shadcn-item": () => import("./shadcn/item/preview"),
  "shadcn-kbd": () => import("./shadcn/kbd/preview"),
  "shadcn-label": () => import("./shadcn/label/preview"),
  "shadcn-marker": () => import("./shadcn/marker/preview"),
  "shadcn-menubar": () => import("./shadcn/menubar/preview"),
  "shadcn-message": () => import("./shadcn/message/preview"),
  "shadcn-message-scroller": () => import("./shadcn/message-scroller/preview"),
  "shadcn-native-select": () => import("./shadcn/native-select/preview"),
  "shadcn-navigation-menu": () => import("./shadcn/navigation-menu/preview"),
  "shadcn-pagination": () => import("./shadcn/pagination/preview"),
  "shadcn-popover": () => import("./shadcn/popover/preview"),
  "shadcn-progress": () => import("./shadcn/progress/preview"),
  "shadcn-questionnaire": () => import("./shadcn/questionnaire/preview"),
  "shadcn-radio-group": () => import("./shadcn/radio-group/preview"),
  "shadcn-resizable": () => import("./shadcn/resizable/preview"),
  "shadcn-scroll-area": () => import("./shadcn/scroll-area/preview"),
  "shadcn-select": () => import("./shadcn/select/preview"),
  "shadcn-separator": () => import("./shadcn/separator/preview"),
  "shadcn-sheet": () => import("./shadcn/sheet/preview"),
  "shadcn-sidebar": () => import("./shadcn/sidebar/preview"),
  "shadcn-skeleton": () => import("./shadcn/skeleton/preview"),
  "shadcn-slider": () => import("./shadcn/slider/preview"),
  "shadcn-sonner": () => import("./shadcn/sonner/preview"),
  "shadcn-spinner": () => import("./shadcn/spinner/preview"),
  "shadcn-switch": () => import("./shadcn/switch/preview"),
  "shadcn-table": () => import("./shadcn/table/preview"),
  "shadcn-tabs": () => import("./shadcn/tabs/preview"),
  "shadcn-textarea": () => import("./shadcn/textarea/preview"),
  "shadcn-toast": () => import("./shadcn/toast/preview"),
  "shadcn-toggle": () => import("./shadcn/toggle/preview"),
  "shadcn-toggle-group": () => import("./shadcn/toggle-group/preview"),
  "shadcn-tooltip": () => import("./shadcn/tooltip/preview"),
  "shadcn-typography": () => import("./shadcn/typography/preview"),
  "magicui-marquee": () => import("./magicui/marquee/preview"),
  "magicui-terminal": () => import("./magicui/terminal/preview"),
  "magicui-hero-video-dialog": () => import("./magicui/hero-video-dialog/preview"),
  "magicui-bento-grid": () => import("./magicui/bento-grid/preview"),
  "magicui-animated-list": () => import("./magicui/animated-list/preview"),
  "magicui-dock": () => import("./magicui/dock/preview"),
  "magicui-globe": () => import("./magicui/globe/preview"),
  "magicui-tweet-card": () => import("./magicui/tweet-card/preview"),
  "magicui-orbiting-circles": () => import("./magicui/orbiting-circles/preview"),
  "magicui-avatar-circles": () => import("./magicui/avatar-circles/preview"),
  "magicui-icon-cloud": () => import("./magicui/icon-cloud/preview"),
  "magicui-lens": () => import("./magicui/lens/preview"),
  "magicui-pointer": () => import("./magicui/pointer/preview"),
  "magicui-smooth-cursor": () => import("./magicui/smooth-cursor/preview"),
  "magicui-progressive-blur": () => import("./magicui/progressive-blur/preview"),
  "magicui-dotted-map": () => import("./magicui/dotted-map/preview"),
  "magicui-animated-beam": () => import("./magicui/animated-beam/preview"),
  "magicui-border-beam": () => import("./magicui/border-beam/preview"),
  "magicui-shine-border": () => import("./magicui/shine-border/preview"),
  "magicui-magic-card": () => import("./magicui/magic-card/preview"),
  "magicui-glare-hover": () => import("./magicui/glare-hover/preview"),
  "magicui-meteors": () => import("./magicui/meteors/preview"),
  "magicui-confetti": () => import("./magicui/confetti/preview"),
  "magicui-particles": () => import("./magicui/particles/preview"),
  "magicui-animated-theme-toggler": () => import("./magicui/animated-theme-toggler/preview"),
  "magicui-blur-fade": () => import("./magicui/blur-fade/preview"),
  "magicui-text-animate": () => import("./magicui/text-animate/preview"),
  "magicui-typing-animation": () => import("./magicui/typing-animation/preview"),
  "magicui-line-shadow-text": () => import("./magicui/line-shadow-text/preview"),
  "magicui-aurora-text": () => import("./magicui/aurora-text/preview"),
  "magicui-video-text": () => import("./magicui/video-text/preview"),
  "magicui-number-ticker": () => import("./magicui/number-ticker/preview"),
  "magicui-animated-shiny-text": () => import("./magicui/animated-shiny-text/preview"),
  "magicui-animated-gradient-text": () => import("./magicui/animated-gradient-text/preview"),
  "magicui-text-reveal": () => import("./magicui/text-reveal/preview"),
  "magicui-dia-text-reveal": () => import("./magicui/dia-text-reveal/preview"),
  "magicui-hyper-text": () => import("./magicui/hyper-text/preview"),
  "magicui-word-rotate": () => import("./magicui/word-rotate/preview"),
  "magicui-scroll-based-velocity": () => import("./magicui/scroll-based-velocity/preview"),
  "magicui-sparkles-text": () => import("./magicui/sparkles-text/preview"),
  "magicui-morphing-text": () => import("./magicui/morphing-text/preview"),
  "magicui-spinning-text": () => import("./magicui/spinning-text/preview"),
  "magicui-highlighter": () => import("./magicui/highlighter/preview"),
  "magicui-text-3d-flip": () => import("./magicui/text-3d-flip/preview"),
  "magicui-safari": () => import("./magicui/safari/preview"),
  "magicui-iphone": () => import("./magicui/iphone/preview"),
  "magicui-android": () => import("./magicui/android/preview"),
  "magicui-rainbow-button": () => import("./magicui/rainbow-button/preview"),
  "magicui-shimmer-button": () => import("./magicui/shimmer-button/preview"),
  "magicui-ripple-button": () => import("./magicui/ripple-button/preview"),
  "magicui-flickering-grid": () => import("./magicui/flickering-grid/preview"),
  "magicui-animated-grid-pattern": () => import("./magicui/animated-grid-pattern/preview"),
  "magicui-retro-grid": () => import("./magicui/retro-grid/preview"),
  "magicui-ripple": () => import("./magicui/ripple/preview"),
  "magicui-dot-pattern": () => import("./magicui/dot-pattern/preview"),
  "magicui-grid-pattern": () => import("./magicui/grid-pattern/preview"),
  "magicui-hexagon-pattern": () => import("./magicui/hexagon-pattern/preview"),
  "magicui-striped-pattern": () => import("./magicui/striped-pattern/preview"),
  "magicui-interactive-grid-pattern": () => import("./magicui/interactive-grid-pattern/preview"),
  "magicui-light-rays": () => import("./magicui/light-rays/preview"),
  "magicui-noise-texture": () => import("./magicui/noise-texture/preview"),
  "magicui-shiny-button": () => import("./magicui/shiny-button/preview"),
  "magicui-file-tree": () => import("./magicui/file-tree/preview"),
  "magicui-code-comparison": () => import("./magicui/code-comparison/preview"),
  "magicui-scroll-progress": () => import("./magicui/scroll-progress/preview"),
  "magicui-neon-gradient-card": () => import("./magicui/neon-gradient-card/preview"),
  "magicui-comic-text": () => import("./magicui/comic-text/preview"),
  "magicui-kinetic-text": () => import("./magicui/kinetic-text/preview"),
  "magicui-cool-mode": () => import("./magicui/cool-mode/preview"),
  "magicui-pixel-image": () => import("./magicui/pixel-image/preview"),
  "magicui-pulsating-button": () => import("./magicui/pulsating-button/preview"),
  "magicui-warp-background": () => import("./magicui/warp-background/preview"),
  "magicui-interactive-hover-button": () => import("./magicui/interactive-hover-button/preview"),
  "magicui-animated-circular-progress-bar": () =>
    import("./magicui/animated-circular-progress-bar/preview"),
  "magicui-backlight": () => import("./magicui/backlight/preview"),
  "magicui-glyph-matrix": () => import("./magicui/glyph-matrix/preview"),
  "animata-animated-beam": () => import("./animata/animated-beam/preview"),
  "animata-blurry-blob": () => import("./animata/blurry-blob/preview"),
  "animata-boids-ecosystem": () => import("./animata/boids-ecosystem/preview"),
  "animata-diagonal-lines": () => import("./animata/diagonal-lines/preview"),
  "animata-dot": () => import("./animata/dot/preview"),
  "animata-grid": () => import("./animata/grid/preview"),
  "animata-interactive-grid": () => import("./animata/interactive-grid/preview"),
  "animata-moving-gradient": () => import("./animata/moving-gradient/preview"),
  "animata-shooting-stars": () => import("./animata/shooting-stars/preview"),
  "animata-zigzag": () => import("./animata/zigzag/preview"),
  "animata-eight": () => import("./animata/eight/preview"),
  "animata-gradient": () => import("./animata/gradient/preview"),
  "animata-three": () => import("./animata/three/preview"),
  "animata-ai-button": () => import("./animata/ai-button/preview"),
  "animata-algolia-blue-button": () => import("./animata/algolia-blue-button/preview"),
  "animata-algolia-white-button": () => import("./animata/algolia-white-button/preview"),
  "animata-animated-follow-button": () => import("./animata/animated-follow-button/preview"),
  "animata-duolingo": () => import("./animata/duolingo/preview"),
  "animata-get-started-button": () => import("./animata/get-started-button/preview"),
  "animata-ripple-button": () => import("./animata/ripple-button/preview"),
  "animata-shining-button": () => import("./animata/shining-button/preview"),
  "animata-slide-arrow-button": () => import("./animata/slide-arrow-button/preview"),
  "animata-status-button": () => import("./animata/status-button/preview"),
  "animata-swipe-button": () => import("./animata/swipe-button/preview"),
  "animata-toggle-switch": () => import("./animata/toggle-switch/preview"),
  "animata-work-button": () => import("./animata/work-button/preview"),
  "animata-card-comment": () => import("./animata/card-comment/preview"),
  "animata-card-spread": () => import("./animata/card-spread/preview"),
  "animata-card-stack": () => import("./animata/card-stack/preview"),
  "animata-case-study-card": () => import("./animata/case-study-card/preview"),
  "animata-collab-card": () => import("./animata/collab-card/preview"),
  "animata-flip-card": () => import("./animata/flip-card/preview"),
  "animata-github-card-shiny": () => import("./animata/github-card-shiny/preview"),
  "animata-github-card-skew": () => import("./animata/github-card-skew/preview"),
  "animata-glowing-card": () => import("./animata/glowing-card/preview"),
  "animata-led-board": () => import("./animata/led-board/preview"),
  "animata-swap-text-card": () => import("./animata/swap-text-card/preview"),
  "animata-animated-border-trail": () => import("./animata/animated-border-trail/preview"),
  "animata-announcement-ribbon": () => import("./animata/announcement-ribbon/preview"),
  "animata-cursor-tracker": () => import("./animata/cursor-tracker/preview"),
  "animata-marquee": () => import("./animata/marquee/preview"),
  "animata-sibling-focus-nav": () => import("./animata/sibling-focus-nav/preview"),
  "animata-flower-menu": () => import("./animata/flower-menu/preview"),
  "animata-speed-dial": () => import("./animata/speed-dial/preview"),
  "animata-bar-chart": () => import("./animata/bar-chart/preview"),
  "animata-donut-chart": () => import("./animata/donut-chart/preview"),
  "animata-gauge-chart": () => import("./animata/gauge-chart/preview"),
  "animata-progress": () => import("./animata/progress/preview"),
  "animata-ring-chart": () => import("./animata/ring-chart/preview"),
  "animata-hero-section-text-hover": () => import("./animata/hero-section-text-hover/preview"),
  "animata-product-features": () => import("./animata/product-features/preview"),
  "animata-shape-shifter": () => import("./animata/shape-shifter/preview"),
  "animata-slack-intro": () => import("./animata/slack-intro/preview"),
  "animata-hover-interaction": () => import("./animata/hover-interaction/preview"),
  "animata-icon-ripple": () => import("./animata/icon-ripple/preview"),
  "animata-disclose-image": () => import("./animata/disclose-image/preview"),
  "animata-images-reveal": () => import("./animata/images-reveal/preview"),
  "animata-skew-image": () => import("./animata/skew-image/preview"),
  "animata-tilted-cover": () => import("./animata/tilted-cover/preview"),
  "animata-trailing-image": () => import("./animata/trailing-image/preview"),
  "animata-avatar-list": () => import("./animata/avatar-list/preview"),
  "animata-flipping-cards": () => import("./animata/flipping-cards/preview"),
  "animata-menu-animation": () => import("./animata/menu-animation/preview"),
  "animata-orbiting-items": () => import("./animata/orbiting-items/preview"),
  "animata-orbiting-items-3-d": () => import("./animata/orbiting-items-3-d/preview"),
  "animata-reveal-image": () => import("./animata/reveal-image/preview"),
  "animata-transaction-list": () => import("./animata/transaction-list/preview"),
  "animata-modal": () => import("./animata/modal/preview"),
  "animata-split-reveal": () => import("./animata/split-reveal/preview"),
  "animata-vertical-tiles": () => import("./animata/vertical-tiles/preview"),
  "animata-animatedtimeline": () => import("./animata/animatedtimeline/preview"),
  "animata-spinner": () => import("./animata/spinner/preview"),
  "animata-stacked-sections": () => import("./animata/stacked-sections/preview"),
  "animata-code": () => import("./animata/code/preview"),
  "animata-cookie-banner": () => import("./animata/cookie-banner/preview"),
  "animata-list": () => import("./animata/list/preview"),
  "animata-receipt": () => import("./animata/receipt/preview"),
  "animata-report": () => import("./animata/report/preview"),
  "animata-wide-card": () => import("./animata/wide-card/preview"),
  "animata-fluid-tabs": () => import("./animata/fluid-tabs/preview"),
  "animata-gooey-tabs": () => import("./animata/gooey-tabs/preview"),
  "animata-shift-tabs": () => import("./animata/shift-tabs/preview"),
  "animata-animated-gradient-text": () => import("./animata/animated-gradient-text/preview"),
  "animata-blur-out-up": () => import("./animata/blur-out-up/preview"),
  "animata-bold-copy": () => import("./animata/bold-copy/preview"),
  "animata-bottom-up-letters": () => import("./animata/bottom-up-letters/preview"),
  "animata-circular-text": () => import("./animata/circular-text/preview"),
  "animata-counter": () => import("./animata/counter/preview"),
  "animata-cycle-text": () => import("./animata/cycle-text/preview"),
  "animata-double-underline": () => import("./animata/double-underline/preview"),
  "animata-fade-through": () => import("./animata/fade-through/preview"),
  "animata-focus-blur-resolve": () => import("./animata/focus-blur-resolve/preview"),
  "animata-gibberish-text": () => import("./animata/gibberish-text/preview"),
  "animata-glitch-text": () => import("./animata/glitch-text/preview"),
  "animata-jitter-text": () => import("./animata/jitter-text/preview"),
  "animata-jumping-text-instagram": () => import("./animata/jumping-text-instagram/preview"),
  "animata-kinetic-center-build": () => import("./animata/kinetic-center-build/preview"),
  "animata-line-by-line-slide": () => import("./animata/line-by-line-slide/preview"),
  "animata-mask-reveal-up": () => import("./animata/mask-reveal-up/preview"),
  "animata-metis-text": () => import("./animata/metis-text/preview"),
  "animata-micro-scale-fade": () => import("./animata/micro-scale-fade/preview"),
  "animata-mirror-text": () => import("./animata/mirror-text/preview"),
  "animata-per-character-rise": () => import("./animata/per-character-rise/preview"),
  "animata-per-word-crossfade": () => import("./animata/per-word-crossfade/preview"),
  "animata-roll-text": () => import("./animata/roll-text/preview"),
  "animata-scale-down-fade": () => import("./animata/scale-down-fade/preview"),
  "animata-scroll-reveal": () => import("./animata/scroll-reveal/preview"),
  "animata-shared-axis-y": () => import("./animata/shared-axis-y/preview"),
  "animata-shared-axis-z": () => import("./animata/shared-axis-z/preview"),
  "animata-shimmer-sweep": () => import("./animata/shimmer-sweep/preview"),
  "animata-short-slide-down": () => import("./animata/short-slide-down/preview"),
  "animata-short-slide-right": () => import("./animata/short-slide-right/preview"),
  "animata-soft-blur-in": () => import("./animata/soft-blur-in/preview"),
  "animata-split-text": () => import("./animata/split-text/preview"),
  "animata-spring-scale-in": () => import("./animata/spring-scale-in/preview"),
  "animata-swap-text": () => import("./animata/swap-text/preview"),
  "animata-text-border-animation": () => import("./animata/text-border-animation/preview"),
  "animata-text-explode-imessage": () => import("./animata/text-explode-imessage/preview"),
  "animata-text-flip": () => import("./animata/text-flip/preview"),
  "animata-ticker": () => import("./animata/ticker/preview"),
  "animata-top-down-letters": () => import("./animata/top-down-letters/preview"),
  "animata-typing-text": () => import("./animata/typing-text/preview"),
  "animata-underline-hover-text": () => import("./animata/underline-hover-text/preview"),
  "animata-wave-reveal": () => import("./animata/wave-reveal/preview"),
  "animata-alarm-clock": () => import("./animata/alarm-clock/preview"),
  "animata-battery": () => import("./animata/battery/preview"),
  "animata-battery-level": () => import("./animata/battery-level/preview"),
  "animata-calendar-event": () => import("./animata/calendar-event/preview"),
  "animata-calorie-counter": () => import("./animata/calorie-counter/preview"),
  "animata-clock-with-photo": () => import("./animata/clock-with-photo/preview"),
  "animata-cycling": () => import("./animata/cycling/preview"),
  "animata-delivery-card": () => import("./animata/delivery-card/preview"),
  "animata-direction-card": () => import("./animata/direction-card/preview"),
  "animata-expense-tracker": () => import("./animata/expense-tracker/preview"),
  "animata-flight-widget": () => import("./animata/flight-widget/preview"),
  "animata-fund-widget": () => import("./animata/fund-widget/preview"),
  "animata-live-score": () => import("./animata/live-score/preview"),
  "animata-mobile-detail": () => import("./animata/mobile-detail/preview"),
  "animata-music-widget": () => import("./animata/music-widget/preview"),
  "animata-notes": () => import("./animata/notes/preview"),
  "animata-profile": () => import("./animata/profile/preview"),
  "animata-reminder": () => import("./animata/reminder/preview"),
  "animata-reminder-widget": () => import("./animata/reminder-widget/preview"),
  "animata-score-board": () => import("./animata/score-board/preview"),
  "animata-security-alert": () => import("./animata/security-alert/preview"),
  "animata-shopping-list": () => import("./animata/shopping-list/preview"),
  "animata-sleep-tracker": () => import("./animata/sleep-tracker/preview"),
  "animata-storage-status": () => import("./animata/storage-status/preview"),
  "animata-storage-widget": () => import("./animata/storage-widget/preview"),
  "animata-study-timer": () => import("./animata/study-timer/preview"),
  "animata-vpn-widget": () => import("./animata/vpn-widget/preview"),
  "animata-water-tracker": () => import("./animata/water-tracker/preview"),
  "animata-weather-card": () => import("./animata/weather-card/preview"),
  "animata-weekly-progress": () => import("./animata/weekly-progress/preview"),
  "animateui-components-animate-avatar-group": () =>
    import("./animateui/components-animate-avatar-group/preview"),
  "animateui-components-animate-code": () => import("./animateui/components-animate-code/preview"),
  "animateui-components-animate-code-tabs": () =>
    import("./animateui/components-animate-code-tabs/preview"),
  "animateui-components-animate-cursor": () =>
    import("./animateui/components-animate-cursor/preview"),
  "animateui-components-animate-github-stars-wheel": () =>
    import("./animateui/components-animate-github-stars-wheel/preview"),
  "animateui-components-animate-tabs": () => import("./animateui/components-animate-tabs/preview"),
  "animateui-components-animate-tooltip": () =>
    import("./animateui/components-animate-tooltip/preview"),
  "animateui-components-radix-accordion": () =>
    import("./animateui/components-radix-accordion/preview"),
  "animateui-components-radix-alert-dialog": () =>
    import("./animateui/components-radix-alert-dialog/preview"),
  "animateui-components-radix-checkbox": () =>
    import("./animateui/components-radix-checkbox/preview"),
  "animateui-components-radix-dialog": () => import("./animateui/components-radix-dialog/preview"),
  "animateui-components-radix-dropdown-menu": () =>
    import("./animateui/components-radix-dropdown-menu/preview"),
  "animateui-components-radix-files": () => import("./animateui/components-radix-files/preview"),
  "animateui-components-radix-hover-card": () =>
    import("./animateui/components-radix-hover-card/preview"),
  "animateui-components-radix-popover": () =>
    import("./animateui/components-radix-popover/preview"),
  "animateui-components-radix-preview-link-card": () =>
    import("./animateui/components-radix-preview-link-card/preview"),
  "animateui-components-radix-progress": () =>
    import("./animateui/components-radix-progress/preview"),
  "animateui-components-radix-radio-group": () =>
    import("./animateui/components-radix-radio-group/preview"),
  "animateui-components-radix-sheet": () => import("./animateui/components-radix-sheet/preview"),
  "animateui-components-radix-sidebar": () =>
    import("./animateui/components-radix-sidebar/preview"),
  "animateui-components-radix-switch": () => import("./animateui/components-radix-switch/preview"),
  "animateui-components-radix-tabs": () => import("./animateui/components-radix-tabs/preview"),
  "animateui-components-radix-toggle": () => import("./animateui/components-radix-toggle/preview"),
  "animateui-components-radix-toggle-group": () =>
    import("./animateui/components-radix-toggle-group/preview"),
  "animateui-components-radix-tooltip": () =>
    import("./animateui/components-radix-tooltip/preview"),
  "animateui-components-base-accordion": () =>
    import("./animateui/components-base-accordion/preview"),
  "animateui-components-base-alert-dialog": () =>
    import("./animateui/components-base-alert-dialog/preview"),
  "animateui-components-base-checkbox": () =>
    import("./animateui/components-base-checkbox/preview"),
  "animateui-components-base-dialog": () => import("./animateui/components-base-dialog/preview"),
  "animateui-components-base-files": () => import("./animateui/components-base-files/preview"),
  "animateui-components-base-menu": () => import("./animateui/components-base-menu/preview"),
  "animateui-components-base-popover": () => import("./animateui/components-base-popover/preview"),
  "animateui-components-base-preview-card": () =>
    import("./animateui/components-base-preview-card/preview"),
  "animateui-components-base-preview-link-card": () =>
    import("./animateui/components-base-preview-link-card/preview"),
  "animateui-components-base-progress": () =>
    import("./animateui/components-base-progress/preview"),
  "animateui-components-base-radio": () => import("./animateui/components-base-radio/preview"),
  "animateui-components-base-switch": () => import("./animateui/components-base-switch/preview"),
  "animateui-components-base-tabs": () => import("./animateui/components-base-tabs/preview"),
  "animateui-components-base-toggle": () => import("./animateui/components-base-toggle/preview"),
  "animateui-components-base-toggle-group": () =>
    import("./animateui/components-base-toggle-group/preview"),
  "animateui-components-base-tooltip": () => import("./animateui/components-base-tooltip/preview"),
  "animateui-components-headless-accordion": () =>
    import("./animateui/components-headless-accordion/preview"),
  "animateui-components-headless-checkbox": () =>
    import("./animateui/components-headless-checkbox/preview"),
  "animateui-components-headless-dialog": () =>
    import("./animateui/components-headless-dialog/preview"),
  "animateui-components-headless-popover": () =>
    import("./animateui/components-headless-popover/preview"),
  "animateui-components-headless-switch": () =>
    import("./animateui/components-headless-switch/preview"),
  "animateui-components-headless-tabs": () =>
    import("./animateui/components-headless-tabs/preview"),
  "animateui-components-buttons-button": () =>
    import("./animateui/components-buttons-button/preview"),
  "animateui-components-buttons-copy": () => import("./animateui/components-buttons-copy/preview"),
  "animateui-components-buttons-flip": () => import("./animateui/components-buttons-flip/preview"),
  "animateui-components-buttons-github-stars": () =>
    import("./animateui/components-buttons-github-stars/preview"),
  "animateui-components-buttons-icon": () => import("./animateui/components-buttons-icon/preview"),
  "animateui-components-buttons-liquid": () =>
    import("./animateui/components-buttons-liquid/preview"),
  "animateui-components-buttons-ripple": () =>
    import("./animateui/components-buttons-ripple/preview"),
  "animateui-components-buttons-theme-toggler": () =>
    import("./animateui/components-buttons-theme-toggler/preview"),
  "animateui-components-backgrounds-bubble": () =>
    import("./animateui/components-backgrounds-bubble/preview"),
  "animateui-components-backgrounds-fireworks": () =>
    import("./animateui/components-backgrounds-fireworks/preview"),
  "animateui-components-backgrounds-gradient": () =>
    import("./animateui/components-backgrounds-gradient/preview"),
  "animateui-components-backgrounds-gravity-stars": () =>
    import("./animateui/components-backgrounds-gravity-stars/preview"),
  "animateui-components-backgrounds-hexagon": () =>
    import("./animateui/components-backgrounds-hexagon/preview"),
  "animateui-components-backgrounds-hole": () =>
    import("./animateui/components-backgrounds-hole/preview"),
  "animateui-components-backgrounds-stars": () =>
    import("./animateui/components-backgrounds-stars/preview"),
  "animateui-components-community-flip-card": () =>
    import("./animateui/components-community-flip-card/preview"),
  "animateui-components-community-management-bar": () =>
    import("./animateui/components-community-management-bar/preview"),
  "animateui-components-community-motion-carousel": () =>
    import("./animateui/components-community-motion-carousel/preview"),
  "animateui-components-community-notification-list": () =>
    import("./animateui/components-community-notification-list/preview"),
  "animateui-components-community-pin-list": () =>
    import("./animateui/components-community-pin-list/preview"),
  "animateui-components-community-playful-todolist": () =>
    import("./animateui/components-community-playful-todolist/preview"),
  "animateui-components-community-radial-intro": () =>
    import("./animateui/components-community-radial-intro/preview"),
  "animateui-components-community-radial-menu": () =>
    import("./animateui/components-community-radial-menu/preview"),
  "animateui-components-community-radial-nav": () =>
    import("./animateui/components-community-radial-nav/preview"),
  "animateui-components-community-share-button": () =>
    import("./animateui/components-community-share-button/preview"),
  "animateui-components-community-user-presence-avatar": () =>
    import("./animateui/components-community-user-presence-avatar/preview"),
  "animateui-primitives-animate-avatar-group": () =>
    import("./animateui/primitives-animate-avatar-group/preview"),
  "animateui-primitives-animate-code-block": () =>
    import("./animateui/primitives-animate-code-block/preview"),
  "animateui-primitives-animate-cursor": () =>
    import("./animateui/primitives-animate-cursor/preview"),
  "animateui-primitives-animate-github-stars": () =>
    import("./animateui/primitives-animate-github-stars/preview"),
  "animateui-primitives-animate-motion-grid": () =>
    import("./animateui/primitives-animate-motion-grid/preview"),
  "animateui-primitives-animate-pinned-list": () =>
    import("./animateui/primitives-animate-pinned-list/preview"),
  "animateui-primitives-animate-scroll-progress": () =>
    import("./animateui/primitives-animate-scroll-progress/preview"),
  "animateui-primitives-animate-slot": () => import("./animateui/primitives-animate-slot/preview"),
  "animateui-primitives-animate-spring": () =>
    import("./animateui/primitives-animate-spring/preview"),
  "animateui-primitives-animate-tabs": () => import("./animateui/primitives-animate-tabs/preview"),
  "animateui-primitives-animate-tooltip": () =>
    import("./animateui/primitives-animate-tooltip/preview"),
  "animateui-primitives-radix-accordion": () =>
    import("./animateui/primitives-radix-accordion/preview"),
  "animateui-primitives-radix-alert-dialog": () =>
    import("./animateui/primitives-radix-alert-dialog/preview"),
  "animateui-primitives-radix-checkbox": () =>
    import("./animateui/primitives-radix-checkbox/preview"),
  "animateui-primitives-radix-collapsible": () =>
    import("./animateui/primitives-radix-collapsible/preview"),
  "animateui-primitives-radix-dialog": () => import("./animateui/primitives-radix-dialog/preview"),
  "animateui-primitives-radix-dropdown-menu": () =>
    import("./animateui/primitives-radix-dropdown-menu/preview"),
  "animateui-primitives-radix-files": () => import("./animateui/primitives-radix-files/preview"),
  "animateui-primitives-radix-hover-card": () =>
    import("./animateui/primitives-radix-hover-card/preview"),
  "animateui-primitives-radix-popover": () =>
    import("./animateui/primitives-radix-popover/preview"),
  "animateui-primitives-radix-preview-link-card": () =>
    import("./animateui/primitives-radix-preview-link-card/preview"),
  "animateui-primitives-radix-progress": () =>
    import("./animateui/primitives-radix-progress/preview"),
  "animateui-primitives-radix-radio-group": () =>
    import("./animateui/primitives-radix-radio-group/preview"),
  "animateui-primitives-radix-sheet": () => import("./animateui/primitives-radix-sheet/preview"),
  "animateui-primitives-radix-switch": () => import("./animateui/primitives-radix-switch/preview"),
  "animateui-primitives-radix-tabs": () => import("./animateui/primitives-radix-tabs/preview"),
  "animateui-primitives-radix-toggle": () => import("./animateui/primitives-radix-toggle/preview"),
  "animateui-primitives-radix-toggle-group": () =>
    import("./animateui/primitives-radix-toggle-group/preview"),
  "animateui-primitives-radix-tooltip": () =>
    import("./animateui/primitives-radix-tooltip/preview"),
  "animateui-primitives-base-accordion": () =>
    import("./animateui/primitives-base-accordion/preview"),
  "animateui-primitives-base-alert-dialog": () =>
    import("./animateui/primitives-base-alert-dialog/preview"),
  "animateui-primitives-base-checkbox": () =>
    import("./animateui/primitives-base-checkbox/preview"),
  "animateui-primitives-base-collapsible": () =>
    import("./animateui/primitives-base-collapsible/preview"),
  "animateui-primitives-base-dialog": () => import("./animateui/primitives-base-dialog/preview"),
  "animateui-primitives-base-files": () => import("./animateui/primitives-base-files/preview"),
  "animateui-primitives-base-menu": () => import("./animateui/primitives-base-menu/preview"),
  "animateui-primitives-base-popover": () => import("./animateui/primitives-base-popover/preview"),
  "animateui-primitives-base-preview-card": () =>
    import("./animateui/primitives-base-preview-card/preview"),
  "animateui-primitives-base-preview-link-card": () =>
    import("./animateui/primitives-base-preview-link-card/preview"),
  "animateui-primitives-base-progress": () =>
    import("./animateui/primitives-base-progress/preview"),
  "animateui-primitives-base-radio": () => import("./animateui/primitives-base-radio/preview"),
  "animateui-primitives-base-switch": () => import("./animateui/primitives-base-switch/preview"),
  "animateui-primitives-base-tabs": () => import("./animateui/primitives-base-tabs/preview"),
  "animateui-primitives-base-toggle": () => import("./animateui/primitives-base-toggle/preview"),
  "animateui-primitives-base-toggle-group": () =>
    import("./animateui/primitives-base-toggle-group/preview"),
  "animateui-primitives-base-tooltip": () => import("./animateui/primitives-base-tooltip/preview"),
  "animateui-primitives-headless-checkbox": () =>
    import("./animateui/primitives-headless-checkbox/preview"),
  "animateui-primitives-headless-dialog": () =>
    import("./animateui/primitives-headless-dialog/preview"),
  "animateui-primitives-headless-disclosure": () =>
    import("./animateui/primitives-headless-disclosure/preview"),
  "animateui-primitives-headless-popover": () =>
    import("./animateui/primitives-headless-popover/preview"),
  "animateui-primitives-headless-switch": () =>
    import("./animateui/primitives-headless-switch/preview"),
  "animateui-primitives-headless-tabs": () =>
    import("./animateui/primitives-headless-tabs/preview"),
  "animateui-primitives-buttons-button": () =>
    import("./animateui/primitives-buttons-button/preview"),
  "animateui-primitives-buttons-flip": () => import("./animateui/primitives-buttons-flip/preview"),
  "animateui-primitives-buttons-liquid": () =>
    import("./animateui/primitives-buttons-liquid/preview"),
  "animateui-primitives-buttons-ripple": () =>
    import("./animateui/primitives-buttons-ripple/preview"),
  "animateui-primitives-texts-counting-number": () =>
    import("./animateui/primitives-texts-counting-number/preview"),
  "animateui-primitives-texts-gradient": () =>
    import("./animateui/primitives-texts-gradient/preview"),
  "animateui-primitives-texts-highlight": () =>
    import("./animateui/primitives-texts-highlight/preview"),
  "animateui-primitives-texts-morphing": () =>
    import("./animateui/primitives-texts-morphing/preview"),
  "animateui-primitives-texts-rolling": () =>
    import("./animateui/primitives-texts-rolling/preview"),
  "animateui-primitives-texts-rotating": () =>
    import("./animateui/primitives-texts-rotating/preview"),
  "animateui-primitives-texts-scrolling-number": () =>
    import("./animateui/primitives-texts-scrolling-number/preview"),
  "animateui-primitives-texts-shimmering": () =>
    import("./animateui/primitives-texts-shimmering/preview"),
  "animateui-primitives-texts-sliding-number": () =>
    import("./animateui/primitives-texts-sliding-number/preview"),
  "animateui-primitives-texts-splitting": () =>
    import("./animateui/primitives-texts-splitting/preview"),
  "animateui-primitives-texts-typing": () => import("./animateui/primitives-texts-typing/preview"),
  "animateui-primitives-effects-auto-height": () =>
    import("./animateui/primitives-effects-auto-height/preview"),
  "animateui-primitives-effects-blur": () => import("./animateui/primitives-effects-blur/preview"),
  "animateui-primitives-effects-click": () =>
    import("./animateui/primitives-effects-click/preview"),
  "animateui-primitives-effects-effect": () =>
    import("./animateui/primitives-effects-effect/preview"),
  "animateui-primitives-effects-fade": () => import("./animateui/primitives-effects-fade/preview"),
  "animateui-primitives-effects-highlight": () =>
    import("./animateui/primitives-effects-highlight/preview"),
  "animateui-primitives-effects-image-zoom": () =>
    import("./animateui/primitives-effects-image-zoom/preview"),
  "animateui-primitives-effects-magnetic": () =>
    import("./animateui/primitives-effects-magnetic/preview"),
  "animateui-primitives-effects-particles": () =>
    import("./animateui/primitives-effects-particles/preview"),
  "animateui-primitives-effects-shine": () =>
    import("./animateui/primitives-effects-shine/preview"),
  "animateui-primitives-effects-slide": () =>
    import("./animateui/primitives-effects-slide/preview"),
  "animateui-primitives-effects-theme-toggler": () =>
    import("./animateui/primitives-effects-theme-toggler/preview"),
  "animateui-primitives-effects-tilt": () => import("./animateui/primitives-effects-tilt/preview"),
  "animateui-primitives-effects-zoom": () => import("./animateui/primitives-effects-zoom/preview"),
  "launchui-cta": () => import("./launchui/cta/preview"),
  "launchui-faq": () => import("./launchui/faq/preview"),
  "launchui-footer": () => import("./launchui/footer/preview"),
  "launchui-hero": () => import("./launchui/hero/preview"),
  "launchui-items": () => import("./launchui/items/preview"),
  "launchui-logos": () => import("./launchui/logos/preview"),
  "launchui-navbar": () => import("./launchui/navbar/preview"),
  "launchui-pricing": () => import("./launchui/pricing/preview"),
  "launchui-stats": () => import("./launchui/stats/preview"),
  "launchui-badge": () => import("./launchui/badge/preview"),
  "launchui-button": () => import("./launchui/button/preview"),
  "launchui-glow": () => import("./launchui/glow/preview"),
  "launchui-mockup": () => import("./launchui/mockup/preview"),
  "launchui-screenshot": () => import("./launchui/screenshot/preview"),
  "launchui-fade": () => import("./launchui/fade/preview"),
  "launchui-glass": () => import("./launchui/glass/preview"),
  "originui-accordion": () => import("./originui/accordion/preview"),
  "originui-alert": () => import("./originui/alert/preview"),
  "originui-avatar": () => import("./originui/avatar/preview"),
  "originui-badge": () => import("./originui/badge/preview"),
  "originui-banner": () => import("./originui/banner/preview"),
  "originui-breadcrumb": () => import("./originui/breadcrumb/preview"),
  "originui-button": () => import("./originui/button/preview"),
  "originui-calendar-date-picker": () => import("./originui/calendar-date-picker/preview"),
  "originui-checkbox": () => import("./originui/checkbox/preview"),
  "originui-image-cropper": () => import("./originui/image-cropper/preview"),
  "originui-dialog": () => import("./originui/dialog/preview"),
  "originui-dropdown": () => import("./originui/dropdown/preview"),
  "originui-file-upload": () => import("./originui/file-upload/preview"),
  "originui-event-calendar": () => import("./originui/event-calendar/preview"),
  "originui-input": () => import("./originui/input/preview"),
  "originui-navbar": () => import("./originui/navbar/preview"),
  "originui-notification": () => import("./originui/notification/preview"),
  "originui-pagination": () => import("./originui/pagination/preview"),
  "originui-popover": () => import("./originui/popover/preview"),
  "originui-radio": () => import("./originui/radio/preview"),
  "originui-select": () => import("./originui/select/preview"),
  "originui-slider": () => import("./originui/slider/preview"),
  "originui-stepper": () => import("./originui/stepper/preview"),
  "originui-switch": () => import("./originui/switch/preview"),
  "originui-table": () => import("./originui/table/preview"),
  "originui-tabs": () => import("./originui/tabs/preview"),
  "originui-textarea": () => import("./originui/textarea/preview"),
  "originui-timeline": () => import("./originui/timeline/preview"),
  "originui-tooltip": () => import("./originui/tooltip/preview"),
  "originui-tree": () => import("./originui/tree/preview"),
  "originui-easings": () => import("./originui/easings/preview"),
  "cossui-accordion": () => import("./cossui/accordion/preview"),
  "cossui-alert": () => import("./cossui/alert/preview"),
  "cossui-alert-dialog": () => import("./cossui/alert-dialog/preview"),
  "cossui-autocomplete": () => import("./cossui/autocomplete/preview"),
  "cossui-avatar": () => import("./cossui/avatar/preview"),
  "cossui-badge": () => import("./cossui/badge/preview"),
  "cossui-breadcrumb": () => import("./cossui/breadcrumb/preview"),
  "cossui-button": () => import("./cossui/button/preview"),
  "cossui-calendar": () => import("./cossui/calendar/preview"),
  "cossui-card": () => import("./cossui/card/preview"),
  "cossui-checkbox": () => import("./cossui/checkbox/preview"),
  "cossui-checkbox-group": () => import("./cossui/checkbox-group/preview"),
  "cossui-collapsible": () => import("./cossui/collapsible/preview"),
  "cossui-combobox": () => import("./cossui/combobox/preview"),
  "cossui-command": () => import("./cossui/command/preview"),
  "cossui-context-menu": () => import("./cossui/context-menu/preview"),
  "cossui-date-picker": () => import("./cossui/date-picker/preview"),
  "cossui-dialog": () => import("./cossui/dialog/preview"),
  "cossui-drawer": () => import("./cossui/drawer/preview"),
  "cossui-empty": () => import("./cossui/empty/preview"),
  "cossui-field": () => import("./cossui/field/preview"),
  "cossui-fieldset": () => import("./cossui/fieldset/preview"),
  "cossui-form": () => import("./cossui/form/preview"),
  "cossui-frame": () => import("./cossui/frame/preview"),
  "cossui-group": () => import("./cossui/group/preview"),
  "cossui-input": () => import("./cossui/input/preview"),
  "cossui-input-group": () => import("./cossui/input-group/preview"),
  "cossui-kbd": () => import("./cossui/kbd/preview"),
  "cossui-label": () => import("./cossui/label/preview"),
  "cossui-menu": () => import("./cossui/menu/preview"),
  "cossui-meter": () => import("./cossui/meter/preview"),
  "cossui-number-field": () => import("./cossui/number-field/preview"),
  "cossui-otp-field": () => import("./cossui/otp-field/preview"),
  "cossui-pagination": () => import("./cossui/pagination/preview"),
  "cossui-popover": () => import("./cossui/popover/preview"),
  "cossui-preview-card": () => import("./cossui/preview-card/preview"),
  "cossui-progress": () => import("./cossui/progress/preview"),
  "cossui-radio-group": () => import("./cossui/radio-group/preview"),
  "cossui-scroll-area": () => import("./cossui/scroll-area/preview"),
  "cossui-select": () => import("./cossui/select/preview"),
  "cossui-segmented-control": () => import("./cossui/segmented-control/preview"),
  "cossui-separator": () => import("./cossui/separator/preview"),
  "cossui-sheet": () => import("./cossui/sheet/preview"),
  "cossui-skeleton": () => import("./cossui/skeleton/preview"),
  "cossui-slider": () => import("./cossui/slider/preview"),
  "cossui-spinner": () => import("./cossui/spinner/preview"),
  "cossui-switch": () => import("./cossui/switch/preview"),
  "cossui-table": () => import("./cossui/table/preview"),
  "cossui-tabs": () => import("./cossui/tabs/preview"),
  "cossui-textarea": () => import("./cossui/textarea/preview"),
  "cossui-toast": () => import("./cossui/toast/preview"),
  "cossui-toggle": () => import("./cossui/toggle/preview"),
  "cossui-toggle-group": () => import("./cossui/toggle-group/preview"),
  "cossui-toolbar": () => import("./cossui/toolbar/preview"),
  "cossui-tooltip": () => import("./cossui/tooltip/preview"),
  "cossui-use-media-query": () => import("./cossui/use-media-query/preview"),
  "cossui-use-copy-to-clipboard": () => import("./cossui/use-copy-to-clipboard/preview"),
  "cossui-particles-accordion": () => import("./cossui/particles-accordion/preview"),
  "cossui-particles-alert": () => import("./cossui/particles-alert/preview"),
  "cossui-particles-alert-dialog": () => import("./cossui/particles-alert-dialog/preview"),
  "cossui-particles-autocomplete": () => import("./cossui/particles-autocomplete/preview"),
  "cossui-particles-avatar": () => import("./cossui/particles-avatar/preview"),
  "cossui-particles-badge": () => import("./cossui/particles-badge/preview"),
  "cossui-particles-breadcrumb": () => import("./cossui/particles-breadcrumb/preview"),
  "cossui-particles-button": () => import("./cossui/particles-button/preview"),
  "cossui-particles-calendar": () => import("./cossui/particles-calendar/preview"),
  "cossui-particles-card": () => import("./cossui/particles-card/preview"),
  "cossui-particles-checkbox": () => import("./cossui/particles-checkbox/preview"),
  "cossui-particles-checkbox-group": () => import("./cossui/particles-checkbox-group/preview"),
  "cossui-particles-collapsible": () => import("./cossui/particles-collapsible/preview"),
  "cossui-particles-combobox": () => import("./cossui/particles-combobox/preview"),
  "cossui-particles-command": () => import("./cossui/particles-command/preview"),
  "cossui-particles-context-menu": () => import("./cossui/particles-context-menu/preview"),
  "cossui-particles-date-picker": () => import("./cossui/particles-date-picker/preview"),
  "cossui-particles-dialog": () => import("./cossui/particles-dialog/preview"),
  "cossui-particles-drawer": () => import("./cossui/particles-drawer/preview"),
  "cossui-particles-empty": () => import("./cossui/particles-empty/preview"),
  "cossui-particles-field": () => import("./cossui/particles-field/preview"),
  "cossui-particles-fieldset": () => import("./cossui/particles-fieldset/preview"),
  "cossui-particles-form": () => import("./cossui/particles-form/preview"),
  "cossui-particles-frame": () => import("./cossui/particles-frame/preview"),
  "cossui-particles-group": () => import("./cossui/particles-group/preview"),
  "cossui-particles-input": () => import("./cossui/particles-input/preview"),
  "cossui-particles-input-group": () => import("./cossui/particles-input-group/preview"),
  "cossui-particles-kbd": () => import("./cossui/particles-kbd/preview"),
  "cossui-particles-menu": () => import("./cossui/particles-menu/preview"),
  "cossui-particles-meter": () => import("./cossui/particles-meter/preview"),
  "cossui-particles-navigation": () => import("./cossui/particles-navigation/preview"),
  "cossui-particles-number-field": () => import("./cossui/particles-number-field/preview"),
  "cossui-particles-otp-field": () => import("./cossui/particles-otp-field/preview"),
  "cossui-particles-pagination": () => import("./cossui/particles-pagination/preview"),
  "cossui-particles-popover": () => import("./cossui/particles-popover/preview"),
  "cossui-particles-preview-card": () => import("./cossui/particles-preview-card/preview"),
  "cossui-particles-progress": () => import("./cossui/particles-progress/preview"),
  "cossui-particles-radio-group": () => import("./cossui/particles-radio-group/preview"),
  "cossui-particles-scroll-area": () => import("./cossui/particles-scroll-area/preview"),
  "cossui-particles-select": () => import("./cossui/particles-select/preview"),
  "cossui-particles-separator": () => import("./cossui/particles-separator/preview"),
  "cossui-particles-sheet": () => import("./cossui/particles-sheet/preview"),
  "cossui-particles-skeleton": () => import("./cossui/particles-skeleton/preview"),
  "cossui-particles-slider": () => import("./cossui/particles-slider/preview"),
  "cossui-particles-spinner": () => import("./cossui/particles-spinner/preview"),
  "cossui-particles-switch": () => import("./cossui/particles-switch/preview"),
  "cossui-particles-table": () => import("./cossui/particles-table/preview"),
  "cossui-particles-tabs": () => import("./cossui/particles-tabs/preview"),
  "cossui-particles-textarea": () => import("./cossui/particles-textarea/preview"),
  "cossui-particles-toast": () => import("./cossui/particles-toast/preview"),
  "cossui-particles-toggle": () => import("./cossui/particles-toggle/preview"),
  "cossui-particles-toggle-group": () => import("./cossui/particles-toggle-group/preview"),
  "cossui-particles-toolbar": () => import("./cossui/particles-toolbar/preview"),
  "cossui-particles-tooltip": () => import("./cossui/particles-tooltip/preview"),
  "cultui-hero-dithering": () => import("./cultui/hero-dithering/preview"),
  "cultui-hero-color-panels": () => import("./cultui/hero-color-panels/preview"),
  "cultui-hero-heatmap": () => import("./cultui/hero-heatmap/preview"),
  "cultui-hero-liquid-metal": () => import("./cultui/hero-liquid-metal/preview"),
  "cultui-hero-static-radial-gradient": () =>
    import("./cultui/hero-static-radial-gradient/preview"),
  "cultui-bg-media": () => import("./cultui/bg-media/preview"),
  "cultui-logo-carousel": () => import("./cultui/logo-carousel/preview"),
  "cultui-tweet-grid": () => import("./cultui/tweet-grid/preview"),
  "cultui-gradient-heading": () => import("./cultui/gradient-heading/preview"),
  "cultui-neumorph-button": () => import("./cultui/neumorph-button/preview"),
  "cultui-texture-button": () => import("./cultui/texture-button/preview"),
  "cultui-bg-animate-button": () => import("./cultui/bg-animate-button/preview"),
  "cultui-border-beam-button": () => import("./cultui/border-beam-button/preview"),
  "cultui-metal-button": () => import("./cultui/metal-button/preview"),
  "cultui-cosmic-button": () => import("./cultui/cosmic-button/preview"),
  "cultui-gradient-button-group": () => import("./cultui/gradient-button-group/preview"),
  "cultui-dynamic-island": () => import("./cultui/dynamic-island/preview"),
  "cultui-onboarding": () => import("./cultui/onboarding/preview"),
  "cultui-family-button": () => import("./cultui/family-button/preview"),
  "cultui-toolbar-expandable": () => import("./cultui/toolbar-expandable/preview"),
  "cultui-expandable-screen": () => import("./cultui/expandable-screen/preview"),
  "cultui-expandable": () => import("./cultui/expandable/preview"),
  "cultui-morph-surface": () => import("./cultui/morph-surface/preview"),
  "cultui-side-panel": () => import("./cultui/side-panel/preview"),
  "cultui-family-drawer": () => import("./cultui/family-drawer/preview"),
  "cultui-intro-disclosure": () => import("./cultui/intro-disclosure/preview"),
  "cultui-minimal-card": () => import("./cultui/minimal-card/preview"),
  "cultui-cutout-card": () => import("./cultui/cutout-card/preview"),
  "cultui-neumorph-eyebrow": () => import("./cultui/neumorph-eyebrow/preview"),
  "cultui-texture-card": () => import("./cultui/texture-card/preview"),
  "cultui-shift-card": () => import("./cultui/shift-card/preview"),
  "cultui-mock-browser-window": () => import("./cultui/mock-browser-window/preview"),
  "cultui-code-block": () => import("./cultui/code-block/preview"),
  "cultui-terminal-animation": () => import("./cultui/terminal-animation/preview"),
  "cultui-texture-overlay": () => import("./cultui/texture-overlay/preview"),
  "cultui-distorted-glass": () => import("./cultui/distorted-glass/preview"),
  "cultui-bg-image-texture": () => import("./cultui/bg-image-texture/preview"),
  "cultui-edge-blur": () => import("./cultui/edge-blur/preview"),
  "cultui-dither-image": () => import("./cultui/dither-image/preview"),
  "cultui-grid-beam": () => import("./cultui/grid-beam/preview"),
  "cultui-bg-animated-fractal-grid": () => import("./cultui/bg-animated-fractal-grid/preview"),
  "cultui-canvas-fractal-grid": () => import("./cultui/canvas-fractal-grid/preview"),
  "cultui-stripe-bg-guides": () => import("./cultui/stripe-bg-guides/preview"),
  "cultui-lightboard": () => import("./cultui/lightboard/preview"),
  "cultui-shader-lens-blur": () => import("./cultui/shader-lens-blur/preview"),
  "cultui-svg-shapes": () => import("./cultui/svg-shapes/preview"),
  "cultui-svg-shapes-animated": () => import("./cultui/svg-shapes-animated/preview"),
  "cultui-svg-bands": () => import("./cultui/svg-bands/preview"),
  "cultui-direction-aware-tabs": () => import("./cultui/direction-aware-tabs/preview"),
  "cultui-floating-panel": () => import("./cultui/floating-panel/preview"),
  "cultui-popover": () => import("./cultui/popover/preview"),
  "cultui-popover-form": () => import("./cultui/popover-form/preview"),
  "cultui-dock": () => import("./cultui/dock/preview"),
  "cultui-color-picker": () => import("./cultui/color-picker/preview"),
  "cultui-choice-poll": () => import("./cultui/choice-poll/preview"),
  "cultui-feature-poll": () => import("./cultui/feature-poll/preview"),
  "cultui-feature-voting": () => import("./cultui/feature-voting/preview"),
  "cultui-vote-tally": () => import("./cultui/vote-tally/preview"),
  "cultui-poll-widget": () => import("./cultui/poll-widget/preview"),
  "cultui-prompt-library": () => import("./cultui/prompt-library/preview"),
  "cultui-ai-instructions": () => import("./cultui/ai-instructions/preview"),
  "cultui-timer": () => import("./cultui/timer/preview"),
  "cultui-sortable-list": () => import("./cultui/sortable-list/preview"),
  "cultui-three-d-carousel": () => import("./cultui/three-d-carousel/preview"),
  "cultui-hover-video-player": () => import("./cultui/hover-video-player/preview"),
  "cultui-youtube-video-player": () => import("./cultui/youtube-video-player/preview"),
  "cultui-feature-carousel": () => import("./cultui/feature-carousel/preview"),
  "cultui-loading-carousel": () => import("./cultui/loading-carousel/preview"),
  "cultui-text-animate": () => import("./cultui/text-animate/preview"),
  "cultui-typewriter": () => import("./cultui/typewriter/preview"),
  "cultui-animated-number": () => import("./cultui/animated-number/preview"),
  "cultui-pixel-heading-character": () => import("./cultui/pixel-heading-character/preview"),
  "cultui-pixel-heading-word": () => import("./cultui/pixel-heading-word/preview"),
  "cultui-pixel-paragraph-words": () => import("./cultui/pixel-paragraph-words/preview"),
  "cultui-pixel-paragraph-words-inverse": () =>
    import("./cultui/pixel-paragraph-words-inverse/preview"),
  "cultui-text-gif": () => import("./cultui/text-gif/preview"),
  "cultui-squiggle-arrow": () => import("./cultui/squiggle-arrow/preview"),
  "kiboui-avatar-stack": () => import("./kiboui/avatar-stack/preview"),
  "kiboui-cursor": () => import("./kiboui/cursor/preview"),
  "kiboui-calendar": () => import("./kiboui/calendar/preview"),
  "kiboui-gantt": () => import("./kiboui/gantt/preview"),
  "kiboui-code-block": () => import("./kiboui/code-block/preview"),
  "kiboui-contribution-graph": () => import("./kiboui/contribution-graph/preview"),
  "kiboui-choicebox": () => import("./kiboui/choicebox/preview"),
  "kiboui-combobox": () => import("./kiboui/combobox/preview"),
  "kiboui-dropzone": () => import("./kiboui/dropzone/preview"),
  "kiboui-credit-card": () => import("./kiboui/credit-card/preview"),
  "kiboui-announcement": () => import("./kiboui/announcement/preview"),
  "kiboui-banner": () => import("./kiboui/banner/preview"),
  "kiboui-color-picker": () => import("./kiboui/color-picker/preview"),
  "kiboui-comparison": () => import("./kiboui/comparison/preview"),
  "kiboui-deck": () => import("./kiboui/deck/preview"),
  "kiboui-dialog-stack": () => import("./kiboui/dialog-stack/preview"),
  "kiboui-editor": () => import("./kiboui/editor/preview"),
  "kiboui-glimpse": () => import("./kiboui/glimpse/preview"),
};
